name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn compile
        
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Test with Maven
        run: mvn test
        
      - uses: actions/upload-artifact@v3
        with:
          name: game2048.war
          path: target/game2048.war
    
  package:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Package
        run: mvn package
        
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            target/surefire-reports/*
            target/site/jacoco/*
        
  deploy:
    needs: package
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v3
        with: 
          name: game2048.war
          
      - name: Deploy
        run: cp game2048.war /usr/local/tomcat/webapps
      
