# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          
      - name: Build with Maven
        run: mvn compile
        
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Test with Maven
        run: mvn test
    
  package:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Package
        run: mvn package
        
  deploy:
    needs: package
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: cp target/game2048.war /usr/local/tomcat/webapps
      
